name: Deploy Ubuntu VM with PowerShell

on:
  workflow_dispatch:

jobs:
  deploy-vm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Az Module, Login, and Deploy VM
        shell: pwsh
        env:
          AZURE_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          AZURE_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
          AZURE_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
        run: |
          Install-Module -Name Az -AllowClobber -Scope CurrentUser -Force -ErrorAction Stop
          Import-Module Az -ErrorAction Stop
          $securePassword = ConvertTo-SecureString $env:AZURE_CLIENT_SECRET -AsPlainText -Force
          $cred = New-Object System.Management.Automation.PSCredential($env:AZURE_CLIENT_ID, $securePassword)
          Connect-AzAccount -ServicePrincipal -Tenant $env:AZURE_TENANT_ID -Credential $cred
          ./vmcreate.ps1
