name: Deploy Ubuntu VM with PowerShell

on:
  workflow_dispatch:

jobs:
  deploy-vm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure Login and Deploy VM
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run PowerShell script to deploy VM
        shell: pwsh
        run: |
          # Import Az module
          Import-Module Az
          # Run your deployment script
          ./vmcreate.ps1
