name: Deploy Ubuntu VM with PowerShell

on:
  workflow_dispatch:  # Manual trigger

jobs:
  deploy-vm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Azure PowerShell
        run: |
          pwsh -Command "Install-Module -Name Az -AllowClobber -Scope CurrentUser -Force"
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run PowerShell script to deploy VM
        shell: pwsh
        run: ./vmcreate.ps1  # Ensure your script is named vmcreate.ps1 and in repo root
